# ????? ??? ????????????!

spring.application.name=lab
spring.thymeleaf.cache=false
server.port=8080
spring.servlet.multipart.max-file-size=50MB
gigachat.authKey=MDQ0YWMxZmYtYTMxOS00NjczLTk5YTQtZGQ5ZTQwOThmMjFkOjJmMDU4YWE5LWE2Y2UtNGU3My1iNWU2LWIxMWM4ZWJmYmZiYw==


spring.datasource.url=jdbc:postgresql://localhost:5432/labdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mongodb.uri=mongodb://admin:admin123@localhost:27017/labdb?authSource=admin
spring.mongodb.database=labdb

spring.profiles.default=mock