spring.application.name=lab-client
server.port=8082
client.server-url=http://localhost:8081
spring.thymeleaf.prefix=classpath:/client/templates/
spring.thymeleaf.cache=false
client.oauth.token-uri=http://localhost:8081/oauth2/token
client.oauth.client-id=client-app
client.oauth.client-secret=secret
client.oauth.scope=api.read
