# ===== ???????? ????????? =====
spring.application.name=lab
server.port=8080
spring.thymeleaf.cache=false
spring.profiles.default=mock
rest.client.base-url=http://localhost:${server.port}

# ===== ???????? ?????? =====
spring.servlet.multipart.max-file-size=50MB

# ===== GIGACHAT API =====
gigachat.authKey=MDQ0YWMxZmYtYTMxOS00NjczLTk5YTQtZGQ5ZTQwOThmMjFkOjJmMDU4YWE5LWE2Y2UtNGU3My1iNWU2LWIxMWM4ZWJmYmZiYw==

# ===== POSTGRESQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/labdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== MONGODB =====
spring.mongodb.uri=mongodb://admin:admin123@localhost:27017/labdb?authSource=admin
spring.mongodb.database=labdb

# ===== JWT ????????? =====

jwt.jwtAccessSecret= WX5bD8z2FkPqJtRvY7uAeHcLmNpKs4V9wCxE1Z3B6yG0UjIiOoQnMlXaSdRfTg
jwt.jwtRefreshSecret= zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
jwt.accessLifetime= PT15M
jwt.refreshLifetime= P30D

# ===== SWAGGER/OPENAPI =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.persist-authorization=true
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=false
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
